/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/ai/': RouteRecordInfo<'/admin/ai/', '/admin/ai', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/files/': RouteRecordInfo<'/admin/files/', '/admin/files', Record<never, never>, Record<never, never>>,
    '/admin/knowledge/': RouteRecordInfo<'/admin/knowledge/', '/admin/knowledge', Record<never, never>, Record<never, never>>,
    '/admin/log/': RouteRecordInfo<'/admin/log/', '/admin/log', Record<never, never>, Record<never, never>>,
    '/admin/notice/': RouteRecordInfo<'/admin/notice/', '/admin/notice', Record<never, never>, Record<never, never>>,
    '/admin/Notice/': RouteRecordInfo<'/admin/Notice/', '/admin/Notice', Record<never, never>, Record<never, never>>,
    '/admin/profile/': RouteRecordInfo<'/admin/profile/', '/admin/profile', Record<never, never>, Record<never, never>>,
    '/admin/settings/': RouteRecordInfo<'/admin/settings/', '/admin/settings', Record<never, never>, Record<never, never>>,
    '/admin/systemConfig/': RouteRecordInfo<'/admin/systemConfig/', '/admin/systemConfig', Record<never, never>, Record<never, never>>,
    '/admin/userManage/': RouteRecordInfo<'/admin/userManage/', '/admin/userManage', Record<never, never>, Record<never, never>>,
    '/admin/userManage/AddUserDialog': RouteRecordInfo<'/admin/userManage/AddUserDialog', '/admin/userManage/AddUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/userManage/EditUserDialog': RouteRecordInfo<'/admin/userManage/EditUserDialog', '/admin/userManage/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/Register/': RouteRecordInfo<'/auth/Register/', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/templates/': RouteRecordInfo<'/templates/', '/templates', Record<never, never>, Record<never, never>>,
    '/templates/analytics': RouteRecordInfo<'/templates/analytics', '/templates/analytics', Record<never, never>, Record<never, never>>,
    '/templates/dashboard': RouteRecordInfo<'/templates/dashboard', '/templates/dashboard', Record<never, never>, Record<never, never>>,
    '/templates/knowledge': RouteRecordInfo<'/templates/knowledge', '/templates/knowledge', Record<never, never>, Record<never, never>>,
    '/templates/stats': RouteRecordInfo<'/templates/stats', '/templates/stats', Record<never, never>, Record<never, never>>,
    '/templates/websocket': RouteRecordInfo<'/templates/websocket', '/templates/websocket', Record<never, never>, Record<never, never>>,
    '/user/history/': RouteRecordInfo<'/user/history/', '/user/history', Record<never, never>, Record<never, never>>,
    '/user/knowledge/': RouteRecordInfo<'/user/knowledge/', '/user/knowledge', Record<never, never>, Record<never, never>>,
    '/user/notifications/': RouteRecordInfo<'/user/notifications/', '/user/notifications', Record<never, never>, Record<never, never>>,
    '/user/stats/': RouteRecordInfo<'/user/stats/', '/user/stats', Record<never, never>, Record<never, never>>,
    '/user/system_film/': RouteRecordInfo<'/user/system_film/', '/user/system_film', Record<never, never>, Record<never, never>>,
    '/userInfo/': RouteRecordInfo<'/userInfo/', '/userInfo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/ai/index.vue': {
      routes: '/admin/ai/'
      views: never
    }
    'src/pages/admin/dashboard/index.vue': {
      routes: '/admin/dashboard/'
      views: never
    }
    'src/pages/admin/files/index.vue': {
      routes: '/admin/files/'
      views: never
    }
    'src/pages/admin/knowledge/index.vue': {
      routes: '/admin/knowledge/'
      views: never
    }
    'src/pages/admin/log/index.vue': {
      routes: '/admin/log/'
      views: never
    }
    'src/pages/admin/notice/index.vue': {
      routes: '/admin/notice/'
      views: never
    }
    'src/pages/admin/Notice/index.vue': {
      routes: '/admin/Notice/'
      views: never
    }
    'src/pages/admin/profile/index.vue': {
      routes: '/admin/profile/'
      views: never
    }
    'src/pages/admin/settings/index.vue': {
      routes: '/admin/settings/'
      views: never
    }
    'src/pages/admin/systemConfig/index.vue': {
      routes: '/admin/systemConfig/'
      views: never
    }
    'src/pages/admin/userManage/index.vue': {
      routes: '/admin/userManage/'
      views: never
    }
    'src/pages/admin/userManage/AddUserDialog.vue': {
      routes: '/admin/userManage/AddUserDialog'
      views: never
    }
    'src/pages/admin/userManage/EditUserDialog.vue': {
      routes: '/admin/userManage/EditUserDialog'
      views: never
    }
    'src/pages/auth/login/index.vue': {
      routes: '/auth/login/'
      views: never
    }
    'src/pages/auth/Register/index.vue': {
      routes: '/auth/Register/'
      views: never
    }
    'src/pages/templates/index.vue': {
      routes: '/templates/'
      views: never
    }
    'src/pages/templates/analytics.vue': {
      routes: '/templates/analytics'
      views: never
    }
    'src/pages/templates/dashboard.vue': {
      routes: '/templates/dashboard'
      views: never
    }
    'src/pages/templates/knowledge.vue': {
      routes: '/templates/knowledge'
      views: never
    }
    'src/pages/templates/stats.vue': {
      routes: '/templates/stats'
      views: never
    }
    'src/pages/templates/websocket.vue': {
      routes: '/templates/websocket'
      views: never
    }
    'src/pages/user/history/index.vue': {
      routes: '/user/history/'
      views: never
    }
    'src/pages/user/knowledge/index.vue': {
      routes: '/user/knowledge/'
      views: never
    }
    'src/pages/user/notifications/index.vue': {
      routes: '/user/notifications/'
      views: never
    }
    'src/pages/user/stats/index.vue': {
      routes: '/user/stats/'
      views: never
    }
    'src/pages/user/system_film/index.vue': {
      routes: '/user/system_film/'
      views: never
    }
    'src/pages/userInfo/index.vue': {
      routes: '/userInfo/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
